---
title: "Performance and Salaries of NBA Players"
author: "Brandon Pearl, Nicolas Min, Ryan Ice, and Tram Pham"
date: "November 30, 2016"

output:
  beamer_presentation: default
  css: styles.css
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Presentation Outline 
- <small>Project Description</small>
- Source of Data 
- Methodology 
- EDA
- Results 
- Conclusion

## Project Description {#projectdescription .emphasized}
- Analyzing basketball players data from the NBA League in the 2015-2016 season


 Our Aim:  In the 2015-2016 season, how do the skills of a player relate to his salary?



## Source of Data
- Basketball Reference
- Roster, Total, and Salaries tables

## Methodology - Data Acquisition
- Two phases of webscraping
1. Get list of team abbreviations
2. Get the roster, salary, and totals tables via their IDs


## Methodology - Data Cleaning
- First we cleaned the data, then we merged the tables

## EDA
- Split data into qualitative and quantitative
- Qualitative - used dplyr and frequency to analyze
- Quantitative - used summary() to get a summary of statistics

## Data Analysis - EFF
- EFF = (total points + total rebounds + assists + steals + blocks - missed
field goals - missed free throws - turnovers) / (games played)

## Data Analysis - Salary Aggregates
- Aggregated salary data by team

## Shiny Apps:
- Check out our nifty apps:
1. Team Salaries app - https://stat133.shinyapps.io/team-salaries/
2. Statistic Salaries app - https://stat133.shinyapps.io/stat-salaries/

## Results
- EFF and salary are positively correlated (r = 0.474)
- 

